- awsshell/config.py
Fixes issues with test_keys.py and test_config.py.  Creates the directory that will contain the awsshellrc config file if it doesn't yet exist.  Once it exists, continues with copying the template config file to ~/.aws/shell/awsshellrc.
> Fix tests if ~/.aws/shell/ doesn't exist.

- awsshell/app.py
- awsshell/utils.py
- tests/unit/test_utils.py
Fixes #55 
`tempfile.NamedTemporaryFile` creates a file that cannot be opened twice on windows.  We had to make a similar change in the aws-cli a while back.
> Add cross platform temporary file creation

- awsshell/data/kinesis/2013-12-02/completions-1.json
Most Kinesis Stream API takes stream names as its parameters.
This PR autocompletes Kinesis stream names.
Usage
```
$ aws-shell
$ aws-shell
aws> kinesis describe-stream --stream-name <TAB> # <- completes stream names
```
> add completions for Amazon Kinesis Stream

- awsshell/app.py
- awsshell/index/completion.py
- awsshell/lexer.py
- awsshell/ui.py
- tests/unit/test_load_completions.py
Updated https://github.com/awslabs/aws-shell/issues/27 with the following proposal:
---
A lexer would make it easier to visually distinguish the different components of a command:
aws [options] <command> <subcommand> [parameters]
Default theme: vim
```
theme = vim
```
theme = none
theme = vim
theme = vim
*Note: My terminal colors are customized which might be why we see light gray for `aws>`.*
theme = xcode
> Implements #27: Add lexer/syntax highlighting.

- .travis.yml
- Makefile
- awsshell/__init__.py
- awsshell/app.py
- awsshell/config.py
- awsshell/docs.py
- awsshell/index/completion.py
- awsshell/keys.py
- awsshell/lexer.py
- awsshell/loaders.py
- awsshell/makeindex.py
- awsshell/resource/index.py
- awsshell/style.py
- awsshell/substring.py
- awsshell/toolbar.py
- awsshell/ui.py
- awsshell/utils.py
Before fixing issues or adding feature requests, let's set up `make check` to run cleanly.  I've made a few changes:
1. Change the pylint run to just use `pylint -E`.  Even with a custom pylintrc there's too many false positives.  I'm also not a fan of cluttering code with pylint exclusion comments.
2. Add a `make pylint` that we can occasionally run and manually sift through any issues.
3. Add `make check` as part of the travis builds.
4. Small code cleanup to get `make check` to run cleanly.
The upcoming pull requests will use this as a base branch.
> Ensure clean "make check" output

- README.rst
- awsshell/app.py
- tests/unit/test_app.py
Closes https://github.com/awslabs/aws-shell/issues/76
Note: I'll need to rebase after https://github.com/awslabs/aws-shell/pull/92 is merged.
> Add Cd dot command

- setup.py
Just general future proofing.  Assuming the packages
follow semver (we do for boto3), we shouldn't jump up to
new major versions automatically.
> Lock deps to major versions

- README.rst
- awsshell/app.py
- awsshell/compat.py
- tests/unit/test_app.py
Fixes #88.
* Default editor to vi, not vim.  vi is available on more platforms.
* When we do fail, display a helpful error message instead of crashing.
New behavior:
```
$ EDITOR=some-bad-editor aws-shell
aws> .edit
Unable to launch editor: some-bad-editor
You can configure which editor to use by exporting the EDITOR environment variable.
```
> Handle failure when unable to launch .edit editor

- awsshell/data/glacier/2012-06-01/completions-1.json
Hi,
I noticed that auto-completion was throwing an exception (cf below) for --vault-name.
I think the problem was that VaultName was not mapped correctly.
aws> glacier create-vault --vault-name 
Exception in thread Thread-68:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 624, in run
CompleteEvent(text_inserted=True)))
File "/usr/local/lib/python2.7/dist-packages/awsshell/shellcomplete.py", line 135, in get_completions                                                                                       
.retrieve_candidate_values(service, …
> Fixed auto completion for vault name

- setup.py
The problem and the fix are described here: https://github.com/awslabs/aws-shell/issues/113#issuecomment-205132744
Steps to verify fix:
* Have `Pygments` previously installed, say version `1.6`
* `pip install Pygments==1.6`
* Install aws-shell, Pygments is updated to `2.1.3`
* `pip install aws-shell`
`aws-shell` starts up without issues.
>As for the medium term, note the latest prompt-toolkit 0.60 has actually removed the Pygments dependency entirely: jonathanslenders/python-prompt-toolkit@401cbbb#diff-2eeaed663bd0d25b7e608891384b7298.
When we move to `prompt-toolkit>=0.60` we might need to revisit `Pygments`.  Seems the latest `prompt-toolkit` has similar support built-in.
```
awscli==1.10.17
boto3==1.3.0
botocore==1.4.8
colorama==0.3.3
configobj==5.0.6
docutils==0.12
jmespath==0.9.0 …
```
> Fix #113: Add Pygments>=2.1.3,<3.0.0 requirement

- awsshell/makeindex.py
- tests/integration/test_makeindex.py
Shorthand example generator changed its signature,
so I've updated the aws shell to use the new API.
cc @donnemartin
> Update index gen to use new API

- setup.py
This is now required because of the API change for
generating shorthand examples.
cc @donnemartin
> Bump minimum version of the AWS CLI to 1.10.30

- awsshell/app.py
- awsshell/wizard.py
- tests/unit/test_app.py
- tests/unit/test_wizard.py
* Reading JSON files to dict (basic implementation)
* Converting dict to Python objects
* Creating an Environment that supports storing and retrieval via JMESPath queries
* Applying JMESPath queries to retrieved data
* Getting the next stage via a JMESPath query on the environment or static name
* Resolving an EnvParameters object 
Beyond the backlog features above, some additional functionality has been given (basic) implementations to give some context for the above features. ~~These do not have tests as they require a functioning interaction step (at least mocking them).~~
Edit: After review all functionality below has unit tests as well.
* Wizard loop -- can execute basic wizard specs from start to finish performing each stage
* Basic request retrieval -- can connect with botocore to …
> AWS Shell Wizards -- Base Commit

- awsshell/interaction.py
- awsshell/selectmenu.py
- tests/integration/test_selectmenu.py
- tests/unit/test_interaction.py
- tests/unit/test_selectmenu.py
An implementation of a selection menu using prompt toolkit. This is very similar to the original prompt provided by prompt toolkit but has a few tweaks that are not possible through the parameters exposed by the library itself. Selecting an option from a set of options is a different enough use case that the following features were required: forcing the selection of one of the options, not allowing the editing of options once selected, and showing the prompt without any input from the user. Additionally, it allows me to modify the layout to begin adding a meta information window similar to the shell's docs. 
@JordonPhillips @kyleknap @jamesls
> Select Menu Implementation and Integration

- awsshell/app.py
- tests/integration/test_keys.py
Previously the integration tests for the `CommandLineInterface` object relied on the default `Input` and `Output` objects instantiated which were based on `stdin` and `stdout`. `prompt_tookit` updated to version 1.0.4 which adds checks that the `Input` and `Output` objects are TTYs, which doesn't hold true when the tests are run as IO is redirected. Changed the IO objects to be the same that `prompt_toolkit` uses to test CLI objects.
@JordonPhillips @jamesls
> Fixed integration tests for key bindings.

- tests/integration/test_selectmenu.py
`prompt_toolkit` updated to version 1.0.4 which adds an assertion that the `input`/`output` given to a `CommandLineInterface` be a TTY. This assertion happens at object instantiation which affects the way we do some of our integration tests. 
We currently have some tests in `integration\test_keys.py` and `integration\test_selectmenu.py` that instantiate CLIs and simulate key presses to them by calling `feed` and `process_keys`. This is used to test that key bindings are properly registered and have the correct results on the state of the CLI. However, the CLI's `run` method is not called, meaning that the actual input and output streams seem to not be used. This is what allowed the tests to function previously. Now that there are assertions to verify that the `input` and `output` are TTYs …
> Fix integrations tests to work with prompt_toolkit 1.0.4

- awsshell/interaction.py
- awsshell/wizard.py
- tests/unit/test_interaction.py
- tests/unit/test_wizard.py
Implemented stage history, error recovery and related unit tests.
I would like the `raise error` to be just a bare raise to preserve the stack trace but I fail linting if I do that. I tried using six.reraise instead but this had some issues in unit tests.
cc @JordonPhillips
> Stage History

- awsshell/app.py
- awsshell/wizard.py
- tests/unit/test_app.py
- tests/unit/test_wizard.py
Common and known exceptions will display reasonable error messages and drop back down to the shell. Also added unit tests for the Wizard Handler in the main application that were previously missing.
cc @JordonPhillips
> Handle exceptions in Wizards gracefully

- awsshell/utils.py
- awsshell/wizard.py
- tests/unit/test_utils.py
Prompt toolkit requires that the strings given to it are unicode. Data given to interactions can come from arbitrary sources (service calls) so there must be some mechanism in place ensuring that all strings given to prompt toolkit are of `six.text_type`. This function will recursively search lists and dicts for strings and encode any non-unicode strings as unicode. This is not ideal but is necessary to move forward.
@JordonPhillips @kyleknap
> Force unicode before interaction

- awsshell/wizard.py
- tests/unit/test_wizard.py
When a wizard makes a service request it will now check if the operation supports pagination and load all of the pages upfront.
@JordonPhillips
> Request Retrieval: Pagination

- requirements-test.txt
Some changes to the cli exposed a bug in the stdin/out capturing feature of pytest. I've opened an upstream pull request to fix this and it has been merged: https://github.com/pytest-dev/pytest/pull/1866. Until this version releases next week, I'll be setting the pytest version to be a specific commit including the bugfix to get tests passing again.
@jamesls @kyleknap
> Use specific commit for pytest and bump pytest-cov

- awsshell/interaction.py
- setup.py
- tests/unit/test_interaction.py
A fuzzy select interaction to address some of the feedback Dave had at the wizards planning meeting. This interaction will allow the user to type which will apply the fuzzy search algorithm to filter the list. It will also validate that the input is from the list and reject all others. This is using the `SentenceValidator` class which was failing tests on python 2.6 due to having a set comprehension. I've made a pull request upstream which has been merged as of `prompt_toolkit` v1.0.6. As such the minimum version will be bumped to v1.0.6
@JordonPhillips @jamesls
> Fuzzy Select Interaction

- awsshell/app.py
- awsshell/wizard.py
- tests/unit/test_app.py
- tests/unit/test_wizard.py
Implemented Wizard Delegation. Wizard specifications can now specify a Retrieval step to delegate like so:
```
"Retrieval": {
"Type": "Wizard",
"Resource": "SubWizardName",
"Path": "JMESPath.query"
}
```
A stage's resolution is no longer a void operation, and the data that would be stored in the environment is now also returned at the end of the stage. Upon executing the final stage the return value from it is returned as the final result of executing the wizard. 
This PR also has a couple fixes to old unit tests to increase coverage.
> Delegation

- awsshell/wizard.py
- tests/unit/test_wizard.py
When the environment parameters for a request are being resolved if the query to get the variable returns `None` it will be dropped from the request. This will allow for optional parameters without having to have a request stage for each permutation of parameters.
> Drop key from environment params if None

- awsshell/interaction.py
- awsshell/selectmenu.py
- awsshell/utils.py
- awsshell/wizard.py
- tests/unit/test_interaction.py
- tests/unit/test_utils.py
Implements an Info Select interaction that will show the full JSON body of whatever option you're currently selecting in a similar fashion to the docs pane. I held off on adding this because I was unsure about how to safely render the responses as JSON because the `json.dump` method couldn't handle `datetime` objects. It seems the CLI also had this issue and implemented a `json_encoder` util method to handle it. I've refactored the wizards to use this in all places where something is being rendered as JSON.
@JordonPhillips @kyleknap @jamesls
> Info Select & Rendering responses JSON

- awsshell/wizard.py
- tests/unit/test_wizard.py
This pull requests adds a basic framework for coercing parameters into the correct type. Input taken from prompts will always be strings and for some basic types it is easy enough to cast them implicitly rather than having to define explicitly what type it is in the wizard specification or have a custom interaction.
> Coerce operation params according to model

- requirements-test.txt
Pytest was set to track a specific commit for an upstream bugfix that has now been released in a proper patch version. I've set the version back to this.
@kyleknap @jamesls
> Set pytest back to proper version

- requirements-dev.txt
Travis builds recently started failing due to false positives in pylint (E1102). Despite having our pylint version pinned this issue emerged without any configuration change on our end. I was able to reproduce this failure locally by creating a new virtualenv and following the travis build. Updating the pinned pylint version seems to fix this issue but I'm at a total loss as to how it began failing in the first place.
> Upgrade pinned pylint version

- README.rst
- awsshell/app.py
- awsshell/keys.py
- awsshell/toolbar.py
- awsshell/ui.py
- tests/integration/test_keys.py
- tests/unit/test_toolbar.py
Prompt toolkit deprecated setting the editing mode via the `enable_vi_mode` kwarg on key manager creation. The editing mode is now directly passed to the `Application` instantiation based on the bool instead. 
Additionally, I've enabled mouse support to switch between the default and docs buffers on click and allowed for scrolling in the docs buffer. I've also added a keybinding on `F9` to switch between the buffers. I'm not sure which key is best to toggle back and forth, perhaps there are some standards that vim/emacs have that we could bind this to instead.
Fix for #74 
**Note**: Enabling mouse support in prompt_toolkit seems to have the side effect that the terminals built in text highlighting/selection no longer works. I verified this behavior by looking at pyvim which also does the …
> Editing mode fix and documentation scrolling

- awsshell/app.py
- tests/unit/test_app.py
The `application.history` already has `'aws'` prepended so it is not needed in the list comprehension.
Fixes issue #157
> Don't append 'aws' twice when invoking the .edit command

- README.rst
- awsshell/app.py
Enabling mouse support removes many standard terminal functionalities such as highlighting text to copy paste and scrolling through the prompt history. For now, the trade off in gained vs lost functionality is too great.
> Disable mouse support

- .travis.yml
- awsshell/makeindex.py
Updates documentation related import to support the latest AWS CLI version and adjusts the required cli/sdk versions accordingly.
Fixes #247 
This also removes 2.6 and 3.3 from the Travis matrix as those versions have been EOL for a long time and no longer work on Travis:
```
$ curl -sSf --retry 5 -o python-2.6.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 2.6 archive. The archive may not exist. Please consider a different version.
```
> Update to support the latest aws-cli
